version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    container_name: my-sql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: github_portal
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql-data: